queries = [
    "Find resumes with experience in machine learning and natural language processing.",
    "Retrieve CVs of candidates proficient in Python and deep learning.",
    "Show me resumes of candidates with at least 5 years of software engineering experience.",
    "Find CVs of individuals skilled in both front-end and back-end web development.",
    "Retrieve resumes of candidates with a master's degree in computer science.",
    "Show me CVs of candidates who have worked on projects related to artificial intelligence.",
    "Find resumes of candidates who have managed teams of 10 or more people.",
    "Retrieve CVs of candidates with expertise in cloud computing and DevOps.",
    "Show me resumes of candidates who have a strong background in data analysis and visualization.",
    "Find CVs of individuals who are certified in cybersecurity and have experience in threat detection.",
    "Find resumes with experience in mobile app development and user interface design.",
    "Retrieve CVs of candidates skilled in database management and SQL.",
    "Show me resumes of candidates with a background in finance and risk management.",
    "Find CVs of individuals who have contributed to open-source projects.",
    "Retrieve resumes of candidates with a Ph.D. in computer engineering.",
    "Show me CVs of candidates with experience in agile project management.",
    "Find CVs of candidates who have worked in the healthcare IT sector.",
    "Retrieve resumes of candidates proficient in Java and software architecture.",
    "Show me CVs of candidates who have published research papers in AI conferences.",
    "Find CVs of individuals with strong communication skills and public speaking experience.",
    "Retrieve resumes of candidates who have a track record of successful software product launches.",
    "Show me CVs of candidates who are proficient in multiple programming languages.",
    "Find CVs of individuals who have won hackathons or coding competitions.",
    "Retrieve resumes of candidates with experience in e-commerce platform development.",
    "Show me CVs of candidates who have a background in electrical engineering.",
    "Find CVs of individuals with expertise in natural language processing.",
    "Retrieve resumes of candidates who have worked on large-scale data migration projects.",
    "Show me CVs of candidates who have a background in user experience (UX) design.",
    "Find resumes of candidates who have led machine learning research teams.",
    "Retrieve CVs of candidates with strong problem-solving skills and algorithmic thinking.",
    "Show me resumes of candidates who have a history of mentoring junior developers.",
    "Find CVs of individuals who have experience in software quality assurance.",
    "Retrieve resumes of candidates with experience in building distributed systems.",
    "Show me CVs of candidates who have contributed to AI ethics research.",
    "Find CVs of candidates with expertise in computer vision.",
    "Retrieve resumes of candidates who have worked on IoT (Internet of Things) projects.",
    "Show me CVs of candidates who have a background in data science and statistics.",
    "Find CVs of individuals who have led DevOps transformations in their organizations.",
    "Retrieve resumes of candidates with experience in building web APIs.",
    "Show me CVs of candidates who have a strong portfolio of front-end projects.",
    "Find CVs of candidates who have worked with virtual reality (VR) technologies.",
    "Retrieve resumes of candidates with experience in cybersecurity risk assessment.",
    "Show me CVs of candidates who have a background in computer graphics.",
    "Find CVs of individuals who have contributed to blockchain development.",
    "Retrieve CVs of candidates who have experience with cloud-native application architecture.",
    "Show me resumes of candidates who have managed IT infrastructure for large enterprises.",
    "Find resumes of candidates who have a history of successful software refactorings.",
    "Retrieve CVs of candidates with experience in natural language generation.",
    "Show me CVs of candidates who have a background in software documentation.",
    "Find CVs of individuals who have expertise in big data technologies.",
    "Retrieve resumes of candidates who have worked on real-time data processing systems.",
    "Show me CVs of candidates who have contributed to educational technology projects.",
    "Find CVs of candidates who have experience in financial modeling and analysis.",
    "Retrieve resumes of candidates with a background in computer architecture.",
    "Show me CVs of candidates who have a track record of delivering projects ahead of schedule.",
    "Find CVs of individuals who have expertise in containerization and Docker.",
    "Retrieve CVs of candidates who have experience in game development.",
    "Show me resumes of candidates who have a background in software engineering management.",
    "Find CVs of candidates who have worked on machine learning deployment pipelines.",
    "Retrieve CVs of candidates with experience in cloud security.",
    "Show me CVs of candidates who have a history of collaborating with cross-functional teams.",
    "Find resumes of candidates who have contributed to open-source machine learning libraries.",
    "Retrieve CVs of candidates with experience in medical informatics.",
    "Show me resumes of candidates who have a background in aerospace engineering.",
    "Find CVs of individuals who have led data migration projects between legacy systems.",
    "Retrieve resumes of candidates who have experience in A/B testing for software optimization.",
    "Show me CVs of candidates who have a track record of successful software integration projects.",
    "Find CVs of candidates who have experience in natural language understanding.",
    "Retrieve CVs of candidates with expertise in robotic process automation.",
    "Show me resumes of candidates who have a background in energy systems engineering.",
    "Find CVs of candidates who have worked on chatbot development.",
    "Retrieve CVs of candidates with experience in audio signal processing.",
    "Show me CVs of candidates who have a history of leading continuous integration and deployment (CI/CD) initiatives.",
    "Find CVs of individuals who have expertise in recommendation systems.",
    "Retrieve resumes of candidates who have experience in software localization.",
    "Show me CVs of candidates who have a background in geospatial technology.",
    "Find CVs of candidates who have contributed to cybersecurity research.",
    "Retrieve CVs of candidates with experience in scalable backend architecture.",
    "Show me resumes of candidates who have a history of working in agile scrum teams.",
    "Find CVs of candidates who have experience in data engineering.",
    "Retrieve CVs of candidates with expertise in machine translation.",
    "Show me CVs of candidates who have a background in industrial automation.",
    "Find CVs of individuals who have led digital transformation projects.",
    "Retrieve resumes of candidates who have experience in natural language preprocessing.",
    "Show me CVs of candidates who have a track record of successful software migrations.",
    "Find CVs of candidates who have experience in sentiment analysis.",
    "Retrieve CVs of candidates with expertise in software performance optimization.",
    "Show me CVs of candidates who have a background in cognitive neuroscience.",
    "Find CVs of candidates who have worked on augmented reality (AR) applications.",
    "Retrieve resumes of candidates with experience in ethical hacking.",
    "Show me CVs of candidates who have a history of leading remote development teams.",
    "Find CVs of individuals who have expertise in time series analysis.",
    "Retrieve CVs of candidates with experience in Internet security protocols.",
    "Show me CVs of candidates who have a background in human-computer interaction.",
    "Find resumes of candidates who have contributed to open-source cybersecurity tools.",
    "Retrieve CVs of candidates with expertise in neural network architectures.",
    "Show me CVs of candidates who have a history of successful API design.",
    "Find CVs of candidates who have experience in bioinformatics.",
    "Retrieve resumes of candidates with expertise in software testing automation.",
    "Show me CVs of candidates who have a background in quantum computing.",
    "Find CVs of individuals who have expertise in deep reinforcement learning.",
    "Retrieve CVs of candidates with experience in system administration.",
    "Show me resumes of candidates who have a history of contributing to developer communities.",
    "Find CVs of candidates who have experience in machine learning model deployment.",
    "Retrieve CVs of candidates with expertise in blockchain security.",
    "Show me CVs of candidates who have a background in computational linguistics.",
    "Find CVs of candidates who have contributed to open-source data analysis libraries.",
    "Retrieve resumes of candidates with experience in cyber threat intelligence.",
    "Show me CVs of candidates who have a history of leading software architecture reviews.",
    "Find CVs of individuals who have expertise in quantum algorithms.",
    "Retrieve CVs of candidates with experience in microservices architecture.",
    "Show me CVs of candidates who have a background in renewable energy systems.",
    "Find CVs of candidates who have contributed to open-source robotics projects.",
    "Retrieve resumes of candidates with expertise in anomaly detection.",
    "Show me CVs of candidates who have a history of leading software development lifecycles.",
    "Find CVs of candidates who have experience in reinforcement learning.",
    "Retrieve CVs of candidates with expertise in cloud-native security.",
    "Show me CVs of candidates who have a background in wearable technology.",
    "Find resumes of candidates who have contributed to open-source AI frameworks.",
    "Retrieve CVs of candidates with experience in data visualization.",
    "Show me CVs of candidates who have a history of leading data science teams.",
    "Find CVs of individuals who have expertise in explainable AI.",
    "Retrieve resumes of candidates with experience in mobile security.",
    "Show me CVs of candidates who have a background in biometrics technology."
]